// Run with Node and the already installed Playwright package. No messages are sent.
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
const {chromium} = require('playwright');

(async () => {
 const browser = await chromium.launch({headless:true,channel:'chrome'});
 try {
  const page = await browser.newPage({locale:'fr-FR',viewport:{width:1280,height:1100}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>{
   window.opened=[];
   window.open=url=>{window.opened.push(url);return null};
   Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copied=text}}});
  });
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  await page.evaluate(()=>openContact());
  await page.locator('[data-contact-channel="whatsapp"]').click();
  await page.locator('#contactReason').selectOption('project',{force:true});
  assert.equal(await page.locator('#contactBrief').evaluate(el=>el.required),true);
  assert.equal(await page.locator('#contactReason').evaluate(el=>getComputedStyle(el).opacity),'0');
  await page.locator('#contactContinue').click();
  assert.deepEqual(await page.evaluate(()=>window.opened),[]);
  await page.locator('#contactBrief').fill('Une app de réservation & paiement à Ouaga.');
  await page.locator('#contactContinue').click();
  const whatsapp=new URL((await page.evaluate(()=>window.opened))[0]);
  assert.equal(whatsapp.origin+whatsapp.pathname,'https://wa.me/22658266534');
  assert.match(whatsapp.searchParams.get('text'),/Une app de réservation & paiement à Ouaga\./);
  const email=await page.evaluate(()=>contactURL('email','Conseils & projet','Bonjour !\nÀ bientôt.'));
  assert.equal(new URL(email).pathname,'hey@abdoul.dev');
  assert.equal(new URL(email).searchParams.get('body'),'Bonjour !\nÀ bientôt.');
  await page.locator('[data-contact-channel="linkedin"]').click();
  await page.locator('#contactReason').selectOption('advice',{force:true});
  assert.equal(await page.locator('#contactProjectField').isVisible(),false);
  await page.locator('#contactContinue').click();
  assert.match(await page.evaluate(()=>window.copied),/votre avis/);
  assert.equal(await page.locator('#contactLinkedIn').getAttribute('href'),'https://www.linkedin.com/in/abdouldev/');
  assert.equal(await page.locator('#contactLinkedIn').isVisible(),true);
  await page.evaluate(()=>{closeSheets();openSettings()});
  await page.locator('#languageSelect').selectOption('en',{force:true});
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(await page.locator('.focus-row small').first().textContent(),'Easy to pick up, built around real needs.');
  assert.equal(await page.locator('#contactTitle').textContent(),'Say hello.');
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  await page.evaluate(()=>openSettings());
  await page.locator('#languageSelect').selectOption('fr',{force:true});
  assert.equal(await page.locator('#contactTitle').textContent(),'Parlons-en.');
  await page.evaluate(()=>openSpotlight());
  const headings=await page.locator('.search-section-heading').allTextContents();
  assert(headings.every(text=>!/[0-9]/.test(text)));
  assert(!(await page.locator('#searchResults').textContent()).includes('Appbiz Studio'));
  const rail=page.locator('.search-rail').first();
  await rail.scrollIntoViewIfNeeded();
  const box=await rail.boundingBox();
  await page.mouse.move(box.x+box.width*.8,box.y+30);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width*.2,box.y+30,{steps:12});
  await page.mouse.up();
  await page.waitForTimeout(350);
  assert(await rail.evaluate(el=>el.scrollLeft)>20);
  assert.equal(await page.locator('#spotlight').evaluate(el=>el.classList.contains('open')),true);
  await rail.focus();
  const previous=await rail.evaluate(el=>el.scrollLeft);
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(500);
  assert(await rail.evaluate(el=>el.scrollLeft)>=previous);
  await page.waitForTimeout(300);
  assert(await page.locator('filter feDisplacementMap').count()>0);
  assert(await page.locator('.glass-surface').count()>30);
  assert.deepEqual(errors,[]);
  await page.evaluate(()=>{closeSpotlight();openContact()});
  await page.locator('[data-contact-channel="email"]').click();
  await page.locator('#contactReason').selectOption('project',{force:true});
  await page.locator('#contactBrief').fill('Créer une application mobile pour réserver des services.');
  await page.locator('#contactSheet .sheet-card').evaluate(el=>el.scrollTop=0);
  const buttonSizes=await page.locator('#contactContinue, #contactSheet [data-close-sheet]').evaluateAll(nodes=>nodes.map(el=>{const s=getComputedStyle(el);return [s.height,s.borderRadius,s.fontSize,s.fontWeight]}));
  assert.deepEqual(buttonSizes[0],buttonSizes[1]);
  await page.screenshot({path:'/tmp/portfolio-contact.png'});
  await page.locator('#contactReason + .ui-select-trigger').click();
  assert.equal(await page.locator('.ui-select-menu:popover-open').count(),1);
  await page.screenshot({path:'/tmp/portfolio-dropdown.png'});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#contactSheet').evaluate(el=>el.classList.contains('open')),true);
  await page.evaluate(()=>openPage('apps'));
  await page.waitForTimeout(500);
  assert.equal(await page.locator('#appsPageTitle').textContent(),'Apps');
  assert.equal(await page.locator('#apps-my .portfolio-app-row').count(),10);
  assert.equal(await page.locator('#apps-client .portfolio-app-row').count(),6);
  assert.deepEqual(await page.locator('#appPortfolioSections h2').allTextContents(),['Mes apps','Apps clients']);
  assert.equal(await page.locator('#appsPage [role="tablist"]').count(),0);
  assert(!(await page.locator('#appsPage').textContent()).includes('Appbiz Studio'));
  const layout=await page.locator('#appsPage').evaluate(el=>{
   const page=el.getBoundingClientRect(),card=el.querySelector('.app-section-card').getBoundingClientRect();
   return {left:card.left-page.left};
  });
  assert(layout.left>=17&&layout.left<=21);
  assert.equal(await page.locator('[data-rail-step]').count(),0);
  await page.locator('#apps-my .app-section-rail').focus();
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(600);
  assert(await page.locator('#apps-my .app-section-rail').evaluate(el=>el.scrollLeft)>100);
  await page.evaluate(()=>openSpotlight());
  assert.equal(await page.locator('.search-section[aria-label="Projects"],.search-section[aria-label="Projets"]').count(),0);
  const shadows=await page.locator('.search-column').evaluateAll(nodes=>nodes.map(el=>getComputedStyle(el).boxShadow));
  assert(shadows.every(shadow=>shadow==='none'));
  await page.screenshot({path:'/tmp/search-clean-cards.png'});
  await page.evaluate(()=>{closeSpotlight();setLanguage('en')});
  assert.deepEqual(await page.locator('#appPortfolioSections h2').allTextContents(),['My Apps','Client Apps']);
  await page.evaluate(()=>setLanguage('fr'));
  await page.screenshot({path:'/tmp/apps-two-sections.png'});
  assert.deepEqual(errors,[]);
  console.log('Contact, language persistence, search and desktop scrolling: OK');
 } finally {await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
