const assert=require('node:assert/strict');
const {chromium,devices}=require('playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1000,height:1100},locale:'fr-FR'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  await page.locator('.home-launchers [data-page="about"]').click();
  await page.waitForTimeout(500);
  assert.equal(await page.locator('#homeView').evaluate(el=>el.inert),true);
  await page.locator('#aboutPage .page-body').evaluate(el=>el.scrollTop=160);
  await page.waitForFunction(()=>document.querySelector('#aboutPage .native-header').style.getPropertyValue('--collapse')==='1');
  assert.equal(await page.locator('#aboutPage .native-header').evaluate(el=>el.style.getPropertyValue('--collapse')),'1');
  const edge=await page.locator('.edge-back-zone').boundingBox();
  await page.mouse.move(edge.x+8,edge.y+300);await page.mouse.down();
  await page.mouse.move(edge.x+20,edge.y+300,{steps:4});await page.mouse.up();
  await page.waitForTimeout(320);
  assert.equal(await page.locator('#aboutPage').evaluate(el=>el.classList.contains('active')),true);
  await page.mouse.move(edge.x+8,edge.y+300);await page.mouse.down();
  await page.mouse.move(edge.x+210,edge.y+300,{steps:8});await page.mouse.up();
  await page.waitForFunction(()=>!document.querySelector('#aboutPage').classList.contains('active'));
  assert.equal(await page.locator('#aboutPage').evaluate(el=>el.classList.contains('active')),false);
  await page.locator('.home-dock [data-settings]').click();
  await page.waitForTimeout(450);
  assert.equal(await page.locator('#homeView').evaluate(el=>el.inert),true);
  await page.locator('#textSizeSelect').selectOption('1.3',{force:true});
  assert.equal(await page.locator('#screen').evaluate(el=>el.style.getPropertyValue('--text-scale')),'1.3');
  const grab=await page.locator('#settingsSheet .grabber').boundingBox();
  await page.mouse.move(grab.x+15,grab.y+2);await page.mouse.down();
  await page.mouse.move(grab.x+15,grab.y+190,{steps:6});await page.mouse.up();
  await page.waitForFunction(()=>!document.querySelector('#settingsSheet').classList.contains('open'));
  assert.equal(await page.locator('#settingsSheet').evaluate(el=>el.classList.contains('open')),false);
  await page.reload();
  assert.equal(await page.locator('#screen').evaluate(el=>el.style.getPropertyValue('--text-scale')),'1.3');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>openPage('apps'));
  await page.waitForTimeout(100);
  assert.equal(await page.locator('#appPortfolioSections > section').count(),2);
  await page.evaluate(()=>openContact());await page.waitForTimeout(100);
  await page.locator('#contactSheet [data-close-sheet]').focus();await page.keyboard.press('Tab');
  assert.equal(await page.locator('#contactSheet').evaluate(el=>el.contains(document.activeElement)),true);
  assert.deepEqual(errors,[]);
  await page.screenshot({path:'/tmp/native-large-text.png'});
  const phone=await browser.newPage({...devices['iPhone 13'],locale:'en-US'});
  phone.on('pageerror',e=>errors.push(e.message));await phone.goto(url);
  assert.equal(await phone.locator('.statusbar').isVisible(),false);
  assert.equal(await phone.locator('#island').isVisible(),false);
  await phone.evaluate(()=>openContact());await phone.locator('[data-contact-channel="email"]').click();
  await phone.locator('#contactReason').selectOption('project');
  await phone.locator('#contactBrief').fill('A mobile booking app.');
  // Simulate the visual viewport occupied by the keyboard without changing layout orientation.
  await phone.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,value:390});visualViewport.dispatchEvent(new Event('resize'))});
  await phone.waitForTimeout(300);
  assert.equal(await phone.locator('html').evaluate(el=>el.classList.contains('keyboard-open')),true);
  const fit=await phone.locator('#contactBrief').evaluate(el=>({field:el.getBoundingClientRect().bottom,screen:document.getElementById('screen').getBoundingClientRect().bottom}));
  assert(fit.field<=fit.screen);
  await phone.screenshot({path:'/tmp/native-keyboard.png'});
  assert.deepEqual(errors,[]);
  console.log('Native gestures, large titles, focus, text size, reduced motion and iPhone keyboard: OK');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
