const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.pdf':'application/pdf','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg'};
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(error?'Not found':data)})});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1000,height:1100},locale:'fr-FR',reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const api='https://jeli.abdoul.dev/portfolio-resources';
  let payload,mode='success',requests=0;
  await page.route(api,route=>{requests++;return mode==='offline'?route.abort():route.fulfill({json:payload})});
  await page.route(api+'/files/**',route=>route.fulfill({path:path.join(root,'assets/resources/guide-motion-design-publicitaire.pdf'),contentType:'application/pdf'}));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  payload=await page.evaluate(()=>({version:1,resources:resourceData.fallback}));
  assert.equal(requests,0,'No API or PDF load on the home screen');
  assert.equal(await page.evaluate(()=>performance.getEntriesByType('resource').some(r=>r.name.includes('pdf.min.mjs'))),false);
  await page.evaluate(()=>{setLanguage('fr');openPage('resources')});
  await page.waitForSelector('.resource-card');
  assert.equal(await page.locator('.resource-download').textContent(),'Télécharger');
  assert.match(await page.locator('.resource-download').getAttribute('href'),/\/assets\/resources\/guide-motion-design-publicitaire\.pdf$/);
  await page.locator('.resource-actions button').click();
  await page.waitForSelector('.pdf-page[data-rendered="true"]');
  assert.equal(await page.locator('.pdf-page').count(),5);
  assert(await page.locator('.pdf-page .textLayer span').count()>0);
  await page.locator('#pdfZoom').click();
  assert.equal(await page.locator('#pdfZoom').textContent(),'150%');
  await page.waitForSelector('.pdf-page[data-rendered="true"]');
  await page.locator('#pdfScroll').evaluate(el=>el.scrollTop=el.scrollHeight);
  await page.waitForSelector('.pdf-page[data-page="5"][data-rendered="true"]');
  assert.equal(await page.locator('#pdfProgress').textContent(),'5 / 5');
  assert(await page.locator('#pdfDownload').isVisible());
  const saved=page.waitForEvent('download');await page.locator('#pdfDownload').click();
  const download=await saved;assert.equal(download.suggestedFilename(),'guide-motion-design-publicitaire.pdf');
  assert.equal((await fs.promises.readFile(await download.path())).subarray(0,5).toString(),'%PDF-');
  await page.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.sharedResource=data}}));
  await page.locator('#pdfShare').click();
  assert.equal(await page.evaluate(()=>window.sharedResource.url),'https://www.abdoul.dev/resources/guide-motion-design-publicitaire');
  await page.goto(`http://127.0.0.1:${server.address().port}/?resource=guide-motion-design-publicitaire`);
  await page.waitForSelector('.pdf-page[data-rendered="true"]');
  assert.equal(await page.locator('#readerTitle').textContent(),'Guide motion design publicitaire');
  await page.locator('[data-resource-back]').click();
  assert.equal(await page.locator('.pdf-page').count(),0);
  await page.evaluate(()=>setLanguage('en'));
  assert.equal(await page.locator('.resource-card h2').textContent(),'Advertising motion design guide');
  await page.locator('.resource-actions button').click();
  await page.waitForSelector('.pdf-page[data-rendered="true"]');
  assert.equal(await page.locator('#pdfDownload').textContent(),'Download');
  await page.keyboard.press('Escape');
  assert(await page.locator('#resourcesPage').evaluate(el=>el.classList.contains('active')));
  // Force a refresh through the visible retry action after a new page load.
  mode='offline';await page.reload();await page.evaluate(()=>openPage('resources'));
  await page.waitForSelector('#resourceRetry:not([hidden])');assert.equal(await page.locator('.resource-card').count(),1);
  mode='success';payload={version:1,resources:[]};await page.locator('#resourceRetry').click();
  await page.waitForFunction(()=>document.querySelector('#resourceStatus').textContent==='New resources are coming soon.');
  assert.equal(await page.locator('.resource-card').count(),0);
  payload={version:1,resources:[{id:'unsafe',title:'Bad',link:'javascript:alert(1)'},{id:'safe',title:'<img src=x onerror=alert(1)>',link:'https://example.com',cover:'javascript:alert(1)'}]};
  await page.reload();await page.evaluate(()=>openPage('resources'));await page.waitForSelector('.resource-card');
  assert.equal(await page.locator('.resource-card').count(),1);assert.equal(await page.locator('.resource-card img').count(),0);
  assert.equal(await page.locator('.resource-card h2').textContent(),'<img src=x onerror=alert(1)>');
  assert.deepEqual(errors,[]);
  console.log('Resources: lazy load, PDF text/zoom/scroll/download/share/deep link, FR/EN, offline/empty, unsafe data: OK');
 }finally{await browser.close();server.close()}
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
